[package]
name = "do-not-publish/project-name"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Component = "sleitnick/component@2.4.6"
Knit = "sleitnick/knit@1.4.7"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@1.3.0"